### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by OmaRaad**
- Restructure files, code and logic.

- Implement API communications with Retrofit instead of Volley.

---
This change is [Reviewable](https://reviewable.io/reviews/bitburst-gmbh/bitlabs-android-library/3)

### CODE REVIEW

**Review by tim-oster — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bitburst-gmbh/bitlabs-android-library/3)* status: all files reviewed, 2 unresolved discussions (waiting on @OmaRaad)

___
*[library/src/main/java/ai/bitlabs/sdk/BitLabs.kt, line 48 at r1](https://reviewable.io/reviews/bitburst-gmbh/bitlabs-android-library/3#-MyqvEp_9Y20sqOzgaUt:-MyqvEp_9Y20sqOzgaUu:bt6biz9) ([raw file](https://github.com/bitburst-gmbh/bitlabs-android-library/blob/1ffa7c0da43e8067e170f5acd65553ea60ea8295/library/src/main/java/ai/bitlabs/sdk/BitLabs.kt#L48)):*
> ```Kotlin
> 
>     /** Don't use this method, use [BitLabs.hasSurveys] instead. */
>     fun hasSurveys(gameObject: String) = hasSurveys { hasSurveys ->
> ```

Does the UnityPlayer part here means that everyone using the android sdk also has to include the unity dependencies in their dependencies as well? Is their any way to not include this for non-unity builds?
___
*[library/src/main/java/ai/bitlabs/sdk/data/BitLabsRepository.kt, line 20 at r1](https://reviewable.io/reviews/bitburst-gmbh/bitlabs-android-library/3#-Myqv0dLAIDLl91lFkcv:-Myqv0dLAIDLl91lFkcw:barls) ([raw file](https://github.com/bitburst-gmbh/bitlabs-android-library/blob/1ffa7c0da43e8067e170f5acd65553ea60ea8295/library/src/main/java/ai/bitlabs/sdk/data/BitLabsRepository.kt#L20)):*
> ```Kotlin
> 
>     init {
>         BitLabsAPI.setup(token, uid)
> ```

Out of curiosity: why did you remove the singleton pattern from the BitLabs SDK that a user uses but added a singleton pattern here instead of creating an instance?

**Comment by OmaRaad** [comment]
> Does the UnityPlayer part here means that everyone using the android sdk also has to include the unity dependencies in their dependencies as well? Is their any way to not include this for non-unity builds?

Actually, the Unity3d package is included as a jar file inside the library, so it will be inside this project no matter what. As for using it as a dependency, yes right now it's being used as a dependency; but this has been the case since it was implemented at first. So I didn't change anything. However, I will be looking into making two separate builds, one for unity with unity specific methods, and another one for native use. But I felt, this is beyond the scope of refactoring.

> Out of curiosity: why did you remove the singleton pattern from the BitLabs SDK that a user uses but added a singleton pattern here instead of creating an instance?

I spent a lot of time in this dilemma of whether to make the class a singleton or not. :D
The thing is, our library is used by publishers for just one aspect in their apps, especially video games, for example. So holding an instance throughout the whole app lifecycle and using it only in a narrow process(the rewarding process) feels a little bit awkward. So I decided to let the publishers decide the lifecycle of the class. And decided to do that to the Retrofit interface as well, but then faced an issue with serialisation(Serialisable Interface in Kotlin/Java), so I decided to make only the Retrofit interface a singleton(minimise the number of classes with app lifecycle) just to solve the serialisation issue. And in the future, if I found another solution to my serialisation issue, I will remove the singleton pattern from the app completely.

If you want more information about the serialisation issue, I'm happy to explain more. 
And If you think that a Singleton is still the better approach, let me know.

**Review by tim-oster — COMMENTED** [review]
> Actually, the Unity3d package is included as a jar file inside the library, so it will be inside this project no matter what. As for using it as a dependency, yes right now it's being used as a dependency; but this has been the case since it was implemented at first. So I didn't change anything. However, I will be looking into making two separate builds, one for unity with unity specific methods, and another one for native use. But I felt, this is beyond the scope of refactoring.

The decision sounds reasonable. Feel free to create a ticket in the backlog if you want to look into the unity stuff in the future, otherwise I can also live without it. It was just a thought I had :smile: 

> I spent a lot of time in this dilemma of whether to make the class a singleton or not. :D
The thing is, our library is used by publishers for just one aspect in their apps, especially video games, for example. So holding an instance throughout the whole app lifecycle and using it only in a narrow process(the rewarding process) feels a little bit awkward. So I decided to let the publishers decide the lifecycle of the class. And decided ...

Makes sense, this kind of software design is always tricky. I don't mind too much but I see one issue with this. Since publishers can create multiple instances of `BitLabs`, each with different tokens, etc., this could conflict with only one instance of the API being used in the background because that is only initialized once if I understand the code correctly. Please correct me if I made a wrong assumption.

> *[Reviewable](https://reviewable.io/reviews/bitburst-gmbh/bitlabs-android-library/3#-:-MywHoB38_wtm8cb1A_v:batn8jt)* status: all files reviewed, 2 unresolved discussions (waiting on @OmaRaad)

**Comment by OmaRaad** [comment]
@tim-oster You're right about the logical issue there, it didn't occur to me. I was fixated on solving the Serialization exception xD...

Do you suggest I stick to the Singleton pattern for the BitLabs class? In that case, I'll have to do the same in iOS to have a unified pattern.

Otherwise, I will have to still look into solving the Serialisation issue without making the API class a singleton.

**Review by tim-oster — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bitburst-gmbh/bitlabs-android-library/3)* status: all files reviewed, 2 unresolved discussions (waiting on @OmaRaad)

___
*[example/src/main/java/ai/bitlabs/example/MainActivity.java, line 23 at r2](https://reviewable.io/reviews/bitburst-gmbh/bitlabs-android-library/3#-Mz4RsRED_y2VYGk1PRP:-Mz4RsRED_y2VYGk1PRQ:b-5el62q) ([raw file](https://github.com/bitburst-gmbh/bitlabs-android-library/blob/1f3eb570f22116737ed55d455f5ef2476328fbf1/example/src/main/java/ai/bitlabs/example/MainActivity.java#L23)):*
> ```Java
>         setContentView(R.layout.activity_main);
> 
>         bitLabs.configure("YOUR-APP-TOKEN", "USER-ID");
> ```

Could you call `BitLabs.configure(...)` here directly as well? Because java users are probably confused by the kotlin singleton stuff :smile: 
___
*[library/src/main/java/ai/bitlabs/sdk/BitLabs.kt, line 37 at r2](https://reviewable.io/reviews/bitburst-gmbh/bitlabs-android-library/3#-Mz4S1uJ86DpIaO1jF3E:-Mz4S1uJ86DpIaO1jF3F:b-3qu8a1) ([raw file](https://github.com/bitburst-gmbh/bitlabs-android-library/blob/1f3eb570f22116737ed55d455f5ef2476328fbf1/library/src/main/java/ai/bitlabs/sdk/BitLabs.kt#L37)):*
> ```Kotlin
>         this.token = token
>         this.uid = uid
>         bitLabsRepo = BitLabsRepository()
> ```

Does it make sense here to keep passing the token & uid into the repo? Maybe I am missing the reason, but it does not seem necessary to me, that the Repository needs to be using the singleton although it itself is a regular instance of the class.

**Comment by OmaRaad** [comment]
@tim-oster 

> Could you call BitLabs.configure(...) here directly as well? Because java users are probably confused by the kotlin singleton stuff 

Do you mean that I should make configure() a static method? Or do you mean that I should call the instance here directy as in ```
Bitlabs.INSTANCE.configure(token,uid);
```

I don't suggest that we make it static. I think it's better to let the publishers know it's a singleton instance rather than a static method.

> Does it make sense here to keep passing the token & uid into the repo? Maybe I am missing the reason, but it does not seem necessary to me, that the Repository needs to be using the singleton although it itself is a regular instance of the class.

If I understood you correctly, you want the Repository to be a normal instance, which it is, at the moment. Maybe you also want the API in the repository to be a normal instance as well. I am planning to do that now and push a commit, that's why I made the PR a draft. Please let me know if I didn't understand you well.

**Review by tim-oster — COMMENTED** [review]
> Do you mean that I should make configure() a static method? Or do you mean that I should call the instance here directy as in

I only know that back when I wrote android apps, most SDKs just have a `Sdk.init()` method and have static/singleton state inside them. Just wanted to throw it in here. Keep it in whatever shape you find best.

> If I understood you correctly, you want the Repository to be a normal instance, which it is, at the moment. Maybe you also want the API in the repository to be a normal instance as well. I am planning to do that now and push a commit, that's why I made the PR a draft. Please let me know if I didn't understand you well.

What I meant is:
- IMO the SDK / the interface the publisher interacts with, can be static / singleton because multiple instances will not be required and it is easier to use. This was overall feedback but not the issue that existed.
- The issue was, that you were using a singleton internally which conflicted once a publisher created multiple instances. If I see it correctly, the SDK is now a singleton so that is totally fine.
- The last comment is minor thing / coding style thing: if you create instances in the singleton for repository/api anyway, why not pass the required information when you create them in the singleton rather than having the  repository interacting with the singleton as well?

> *[Reviewable](https://reviewable.io/reviews/bitburst-gmbh/bitlabs-android-library/3#-:-Mz5--5c615SZg6P22T9:brw7ha4)* status: all files reviewed, 2 unresolved discussions (waiting on @OmaRaad)

**Comment by OmaRaad** [comment]
> I only know that back when I wrote android apps, most SDKs just have a `Sdk.init()` method and have static/singleton state inside them. Just wanted to throw it in here. Keep it in whatever shape you find best.

You're right... Kotlin has a built-in singleton syntax, while Java creates singletons using the static keyword... And this also affects the invocation syntax. In Kotlin, you don't have a direct way to make method, like `init()` for example, static. You can only simulate static calls via Singletons.

So a singleton in Kotlin will have an invocation like `BitLabs.init()` in Kotlin and like `BitLabs.INSTANCE.init()` in Java.

There is a workaround for that which is to add a `@JvmStatic` annotation to the method you want, and then it's available to be called statically from Java. However, this will increase the file size drastically(given that it will be added to all the methods in the singleton) as this approach actually creates a static method on top of the non-static one, so all methods will be duplicated. 

That's why I suggest that this stays as it is, and explain it in the Readme documentation we have to Java Devs.

As for the other suggestion, I think your point makes perfect sense, it's better to avoid the access of Singleton inside classes that are members of the Singleton itself.

Please let me know if you have any more suggestion or notes you want me to know about. :)

**Review by tim-oster — APPROVED** [review]
Sounds reasonable! That would be all from my side :smile: 

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bitburst-gmbh/bitlabs-android-library/3#-:-Mz9xm9Y7t6wa953mLzQ:bri3zgz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmaRaad)

**Pull request merged**
